"use client";

import { useState, useCallback, useRef } from "react";
import type { AppState } from "@/app/page";
import { Card, Btn, ProgressBar, BitGrid, StatPill, SectionTitle, DropZone, ErrorBanner } from "./ui";
import { decodeFromVideo, DecodeResult } from "@/lib/decoder";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Filler, Tooltip, Legend);

interface Props {
  state: AppState;
  setVideo: (f: File) => void;
}

export default function DecodeTab({ state, setVideo }: Props) {
  const [progress, setProgress] = useState(0);
  const [phase, setPhase] = useState("");
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<DecodeResult | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  const cancel = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  const onFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0];
      if (f) setVideo(f);
    },
    [setVideo]
  );

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      const f = e.dataTransfer.files?.[0];
      if (f && f.type.startsWith("video/")) setVideo(f);
    },
    [setVideo]
  );

  const runDecode = useCallback(async () => {
    if (!state.videoFile) return;
    const ac = new AbortController();
    abortRef.current = ac;
    setRunning(true);
    setError("");
    setResult(null);

    try {
      setPhase("Extracting & decoding…");
      setProgress(0);
      const decResult = await decodeFromVideo(
        state.videoFile,
        undefined,
        (p) => setProgress(p),
        ac.signal
      );

      setResult(decResult);
      setProgress(100);
      setPhase("");
    } catch (e: unknown) {
      if (e instanceof DOMException && e.name === 'AbortError') {
        setPhase("Cancelled");
      } else {
        setError(e instanceof Error ? e.message : String(e));
      }
    } finally {
      setRunning(false);
      abortRef.current = null;
    }
  }, [state.videoFile]);

  const chartOpts = {
    responsive: true,
    animation: false as const,
    scales: {
      x: {
        ticks: { color: "#4b5563", maxTicksLimit: 10 },
        grid: { color: "#1a1d27" },
        title: { display: true, text: "Frequency (Hz)", color: "#6b7280" },
      },
      y: { ticks: { color: "#4b5563" }, grid: { color: "#1a1d27" } },
    },
    plugins: { legend: { labels: { color: "#9ca3af", font: { size: 11 } } } },
    elements: { point: { radius: 0 }, line: { tension: 0.3 } },
  };

  return (
    <>
      <Card>
        <SectionTitle icon="🔓">Decode a secret message</SectionTitle>

        {/* File upload zone (for encoded video) */}
        <DropZone
          id="decode-file-input"
          onFileChange={onFileChange}
          onDrop={onDrop}
          title="Drag & drop an encoded video, or click to select"
          subtitle="Upload the encoded video generated by the Encode tab"
        />

        {state.videoFile && (
          <div className="mt-5">
            <video src={state.videoUrl} controls className="w-full max-w-[640px] rounded-xl mb-4 ring-1 ring-[var(--border)]" />
            <div className="flex gap-3">
              <Btn onClick={runDecode} disabled={running}>
                {running ? "⏳ Decoding…" : "🔍 Decode"}
              </Btn>
              {running && <Btn variant="danger" onClick={cancel}>✕ Cancel</Btn>}
            </div>
            {running && <ProgressBar value={progress} label={phase} />}
          </div>
        )}

        {error && <ErrorBanner message={error} />}
      </Card>

      {result && (
        <>
          <Card className="animate-slide-up">
            <SectionTitle icon="🎉">Decoded message</SectionTitle>
            <div className="bg-gradient-to-br from-emerald-500/8 to-teal-500/8 border border-emerald-500/20 rounded-2xl p-8 text-center mb-5">
              <p className="text-2xl font-bold bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent break-all">
                {result.message || <span className="text-[var(--text-muted)]">(empty)</span>}
              </p>
            </div>
            <div className="flex flex-wrap gap-4 mb-5">
              <StatPill value={result.bits.length} label="Decoded bits" />
              <StatPill value={result.segments.length} label="Segments" />
              <StatPill value={`${Math.round(result.avgConfidence * 100)}%`} label="Avg. confidence" />
            </div>

            {result.avgConfidence < 0.3 && (
              <div className="bg-amber-500/8 border border-amber-500/25 text-amber-400 rounded-xl p-4 mb-4 text-sm flex items-start gap-3 animate-fade-in">
                <span className="text-base mt-0.5">⚠️</span>
                <span>Low confidence — the decoded message may contain errors.</span>
              </div>
            )}

            <h4 className="text-sm font-medium text-[var(--text-muted)] mb-2">Decoded bits</h4>
            <BitGrid bits={result.bits} />
          </Card>

          {/* Spectrum per segment (first few) */}
          <Card className="animate-slide-up">
            <SectionTitle icon="📊">Spectrum per segment ({Math.min(6, result.segments.length)} of {result.segments.length})</SectionTitle>
            {result.segments.slice(0, 6).map((seg, idx) => (
              <div key={idx} className="mb-4 p-4 bg-[var(--bg-base)] rounded-xl border border-[var(--border)]">
                <div className="flex items-center gap-3 mb-2">
                  <span
                    className={`inline-block px-2.5 py-1 rounded-lg text-xs font-bold ${
                      seg.bit === 0
                        ? "bg-sky-500/10 text-sky-400 border border-sky-500/30"
                        : "bg-rose-500/10 text-rose-400 border border-rose-500/30"
                    }`}
                  >
                    bit={seg.bit}
                  </span>
                  <span className="text-xs text-[var(--text-muted)]">
                    Segment {seg.segment} {seg.isHeader ? "(header)" : "(payload)"} — P0={seg.powerF0} P1={seg.powerF1} — confidence {Math.round(seg.confidence * 100)}%
                  </span>
                </div>
                {seg.specFreqs.length > 0 && (
                  <Line
                    data={{
                      labels: seg.specFreqs.map((f) => f.toFixed(1)),
                      datasets: [{
                        label: "Spectrum",
                        data: seg.specPower,
                        borderColor: seg.bit === 0 ? "#38bdf8" : "#fb7185",
                        backgroundColor: seg.bit === 0 ? "rgba(56,189,248,0.06)" : "rgba(251,113,133,0.06)",
                        fill: true,
                        borderWidth: 1.5,
                      }],
                    }}
                    options={chartOpts}
                  />
                )}
              </div>
            ))}
          </Card>
        </>
      )}
    </>
  );
}
